import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseSbv, lyricAt } from '../src/app/components/wedding/captions.mjs';
const cues = parseSbv(await readFile(new URL('../src/imports/pantika.sbv', import.meta.url), 'utf8'));
assert.ok(cues.length > 30);
assert.equal(lyricAt(cues, 0), undefined);
assert.equal(lyricAt(cues, 11.559).line, 'เชื่อไหม โลกของฉันมันเคยเป็นสีเทา');
assert.equal(lyricAt(cues, 15.464).line, 'จนเกือบจะหมดหวัง');
assert.equal(lyricAt(cues, 23.5), undefined);
assert.equal(lyricAt(cues, 24.5).line, 'จนกระทั่ง');
assert.equal(lyricAt(cues, 200), undefined);
assert.ok(cues.every(cue => cue.end > cue.t && cue.line.trim()));
console.log(`PASS ${cues.length} SBV cues: boundaries, gaps, whitespace and end of song`);
